name: ðŸš€ Deploy AKA E-commerce Website to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy AKA E-commerce Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy AKA E-commerce Website to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/webapps/aka

            echo "Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "Installing dependencies..."
            pnpm install

            echo "Building Next.js app..."
            pnpm run build

            echo "Restarting PM2..."
            pm2 reload ecosystem.config.js

            echo "âœ… Deployment complete!"
